### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by vallentin** [comment]
There is actually already a license. It's at the top in each file, as well as at the bottom of the readme.

**Comment by jpbida** [comment]
Sorry, didn't catch that.

**Comment by vallentin** [comment]
I can add it as a separate file if you really need/want that. Besides that, feel free to use it on your website!

**Comment by jpbida** [comment]
Thanks! It really helps when its easy to find the license. Add the file if
you can.

Best,
Jp

**Comment by vallentin** [comment]
Done!

**Pull request closed without merging**
